name: hm-solar

services:
  solar-collector:
    image: ruby:3.3-slim
    container_name: hm-solar-collector
    volumes:
      - .:/app
      - ../shared:/app/shared
      - gem-cache:/usr/local/bundle
    working_dir: /app
    command: bash -c "bundle install --quiet && bundle exec ruby collect.rb"
    environment:
      BUNDLE_PATH: /usr/local/bundle
      SOLAR_COLLECT_INTERVAL: ${SOLAR_COLLECT_INTERVAL}
      SOLAR_ENPHASE_HOST: ${SOLAR_ENPHASE_HOST}
      SOLAR_ENPHASE_TOKEN: ${SOLAR_ENPHASE_TOKEN}
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  gem-cache:


networks:
  monitoring:
    name: hm-monitoring
    external: true
